[package]
name = "ray_tracer"
version = "0.1.0"
authors = ["Roddy MacCrimmon <r.maccrimm@gmail.com>"]
edition = "2018"

[dependencies]
gl = "0.6.0"
sdl2 = { version = "0.32.0", features = ["bundled"] }
